### ISSUE TITLE
Shaders Source

### ISSUE THREAD

**Issue by alessandromrc** [NarutoUA/fsr_common#2]
Hi @NarutoUA, I wanted to ask you if it is possible to you to release the source of the already compiled shaders that are in the code as it would allow for further optimization and customization.

**Comment by NarutoUA** [comment]
I took precompiled shaders from some game because the actual shaders were released later: https://github.com/GPUOpen-Effects/FidelityFX-FSR

**Comment by alessandromrc** [comment]
> I took precompiled shaders from some game because the actual shaders were released later: https://github.com/GPUOpen-Effects/FidelityFX-FSR

Thank you so much for letting me know! ;)
